<?php

if (function_exists("register_field_group")) {
    register_field_group(array(
        'id' => 'acf_requirement',
        'title' => 'Requirement',
        'fields' => array(
            array(
                'key' => 'field_544e11e181b54',
                'label' => '説明',
                'name' => 'value01',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_5451db8722cfd',
                'label' => '勤務地',
                'name' => 'value_n01',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_544e11f8c2eab',
                'label' => '給与',
                'name' => 'value2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_544e12075e7f2',
                'label' => '仕事内容',
                'name' => 'value03',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_544e1215d5462',
                'label' => '推奨スキル',
                'name' => 'value04',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_544e122564c8f',
                'label' => '福利厚生',
                'name' => 'value05',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'requirements',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_%e3%82%ae%e3%83%a3%e3%83%a9%e3%83%aa%e3%83%bc',
        'title' => 'ギャラリー',
        'fields' => array(
            array(
                'key' => 'field_52c61e1cb16a3',
                'label' => 'ギャラリー画像',
                'name' => 'gallery_img',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_52c61e41b16a4',
                        'label' => 'ギャラリー画像',
                        'name' => 'img',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'id',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array(
                        'key' => 'field_52c61e4eb16a5',
                        'label' => '説明文',
                        'name' => 'img_desc',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => '画像を追加する',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'gallery',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_%e3%82%b9%e3%82%bf%e3%83%83%e3%83%95%e7%b4%b9%e4%bb%8b',
        'title' => 'スタッフ紹介',
        'fields' => array(
            array(
                'key' => 'field_52c6650dfe560',
                'label' => 'スタッフ役職',
                'name' => 'staff_role',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_52c6649afe55f',
                'label' => 'スタッフ画像',
                'name' => 'image',
                'type' => 'image',
                'instructions' => 'スタッフ画像をアップロードしてください',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array(
                'key' => 'field_52d73e09ced27',
                'label' => 'スタッフ画像 02',
                'name' => 'image02',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array(
                'key' => 'field_52d79cdbbe83d',
                'label' => '社員番号',
                'name' => 'staff_number',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'staff',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_%e4%bc%9a%e7%a4%be%e6%a6%82%e8%a6%81',
        'title' => '会社概要',
        'fields' => array(
            array(
                'key' => 'field_52f99dab2528d',
                'label' => '社名',
                'name' => 'name',
                'type' => 'text',
                'instructions' => '社名をいれてください',
                'required' => 1,
                'default_value' => 'EVOLABLE ASIA Co., Ltd',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_52f99dd52528e',
                'label' => '所在地',
                'name' => 'location',
                'type' => 'textarea',
                'instructions' => '所在地をいれてください',
                'required' => 1,
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_52f99e012528f',
                'label' => '電話番号',
                'name' => 'phone_number',
                'type' => 'textarea',
                'instructions' => '電話番号をいれてください',
                'required' => 1,
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_52f99e2a25290',
                'label' => 'FAX',
                'name' => 'fax',
                'type' => 'textarea',
                'instructions' => 'FAX番号をいれてください',
                'required' => 1,
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_52f99e5425291',
                'label' => '役員',
                'name' => 'officer',
                'type' => 'textarea',
                'instructions' => '役員をいれてください',
                'required' => 1,
                'default_value' => '代表取締役社長　薛 悠司',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_52f99e8225292',
                'label' => '設立',
                'name' => 'establishment',
                'type' => 'text',
                'instructions' => '設立年月日をいれてください',
                'required' => 1,
                'default_value' => '2012年3月15日',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_52f99ebd25293',
                'label' => '資本金',
                'name' => 'Capital',
                'type' => 'text',
                'instructions' => '資本金をいれてください',
                'required' => 1,
                'default_value' => '20万米ドル',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_52f99eeb25294',
                'label' => '事業内容',
                'name' => 'desc',
                'type' => 'text',
                'instructions' => '事業内容をいれてください',
                'required' => 1,
                'default_value' => 'ITオフショア開発事業・BPO（ビジネスプロセスアウトソーシング）事業',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_52f99f2425295',
                'label' => 'ライセンスNo.',
                'name' => 'licence',
                'type' => 'textarea',
                'instructions' => 'ライセンスナンバーをいれてください',
                'required' => 1,
                'default_value' => 412023000388,
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_52f99f4c25296',
                'label' => '従業員数',
                'name' => 'staff',
                'type' => 'text',
                'instructions' => '従業員数をいれてください',
                'required' => 1,
                'default_value' => '201名（2013年10月01日現在）',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_52f99f8a25297',
                'label' => '主要取引銀行',
                'name' => 'bank',
                'type' => 'textarea',
                'instructions' => '主要取引銀行を入力してください',
                'required' => 1,
                'default_value' => '主要取引銀行',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array(
                'key' => 'field_52f99fb725298',
                'label' => '経営理念',
                'name' => 'principles',
                'type' => 'text',
                'instructions' => '経営理念をいれてください',
                'required' => 1,
                'default_value' => '働きやすく、みんなが幸せになれる素敵な世界を',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'company_profile',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_%e5%8b%95%e7%94%bb%e7%b4%b9%e4%bb%8b',
        'title' => '動画紹介',
        'fields' => array(
            array(
                'key' => 'field_52c63399433f4',
                'label' => '動画ID',
                'name' => 'movie_code',
                'type' => 'text',
                'instructions' => '例 : http://www.youtube.com/watch?v=JJrQK4_ZUno の場合 JJrQK4_ZUno
v= 以降の文字列を入力してください',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'movie',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_%e5%8f%82%e5%8a%a0%e4%bc%81%e6%a5%ad%e3%81%ae%e5%a3%b0',
        'title' => '参加企業の声',
        'fields' => array(
            array(
                'key' => 'field_52c52a75157c3',
                'label' => 'サブタイトル',
                'name' => 'comp_slogan',
                'type' => 'textarea',
                'instructions' => 'サブタイトル、コピーをいれてください',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'formatting' => 'br',
                'rows' => '',
            ),
            array(
                'key' => 'field_52c52a19157c1',
                'label' => '画像',
                'name' => 'comp_img',
                'type' => 'image',
                'instructions' => '画像をアップロードしてください',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array(
                'key' => 'field_52c52a3d157c2',
                'label' => '企業ロゴ',
                'name' => 'comp_logo',
                'type' => 'image',
                'instructions' => '企業ロゴをいれてください',
                'save_format' => 'id',
                'preview_size' => 'full',
                'library' => 'all',
            ),
            array(
                'key' => 'field_52d76dad27195',
                'label' => '企業リンク',
                'name' => 'comLink',
                'type' => 'text',
                'instructions' => '参加企業へのリンクをいれてください',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5302f563d5725',
                'label' => 'FAQ',
                'name' => 'faq',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5302f5f4d5726',
                        'label' => 'Question',
                        'name' => 'question',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5302f605d5727',
                        'label' => 'Answer',
                        'name' => 'answer',
                        'type' => 'wysiwyg',
                        'column_width' => '',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'yes',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'faqを追加',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'recommend',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_%e5%ae%9f%e7%b8%be',
        'title' => '実績',
        'fields' => array(
            array(
                'key' => 'field_52c65ccf35827',
                'label' => 'サブタイトル',
                'name' => 'slogan',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'formatting' => 'br',
                'rows' => '',
            ),
            array(
                'key' => 'field_52c65cf335828',
                'label' => '画像',
                'name' => 'img',
                'type' => 'image',
                'instructions' => '画像をアップロードしてください',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'labo_result',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'bpo_result',
                    'order_no' => 0,
                    'group_no' => 1,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_%e6%b1%82%e4%ba%ba%e6%83%85%e5%a0%b1',
        'title' => '求人情報',
        'fields' => array(
            array(
                'key' => 'field_52de30546f74c',
                'label' => '求人情報 コンテンツ',
                'name' => 'recruit_content',
                'type' => 'repeater',
                'sub_fields' => array(
                    array(
                        'key' => 'field_52de30726f74d',
                        'label' => '項目',
                        'name' => 'require',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_52de30b86f74e',
                        'label' => '内容',
                        'name' => 'require_content',
                        'type' => 'wysiwyg',
                        'column_width' => '',
                        'default_value' => '',
                        'toolbar' => 'full',
                        'media_upload' => 'yes',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => '求人情報を追加する',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'recruit',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id' => 'acf_%e7%a4%be%e5%86%85%e5%8f%96%e3%82%8a%e7%b5%84%e3%81%bf',
        'title' => '社内取り組み',
        'fields' => array(
            array(
                'key' => 'field_52c6390fe1be3',
                'label' => '画像',
                'name' => 'img',
                'type' => 'image',
                'instructions' => '画像をアップロードしてください',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'circle',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array(
            ),
        ),
        'menu_order' => 0,
    ));
}
